[package]
name = "script-homebrew"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0.22"               #compresses app.tar.gz
tar = "0.4.38"
