///Token field and description for tokenizer (lexer)
#[allow(dead_code, clippy::upper_case_acronyms, clippy::enum_variant_names)]
#[derive(Debug, PartialEq, Clone, Eq, Hash)]
pub enum Token {
    And,
    AndAnd,
    AndEq,
    At,
    Backslash,
    BitCharacterCode7(String),
    BitCharacterCode8(String),
    BlockCommentStart(String),
    BlockCommentStop(String),
    BracketLeft,
    BracketRight,
    BoolFalse,
    BoolTrue,
    Byte(String),
    ByteString(String),
    Caret,
    CaretEq,
    CarriageReturn,
    Character(String),
    Colon,
    Comma,
    CurlyBraceLeft,
    CurlyBraceRight,
    Dollar,
    Dot,
    DotDot,
    DotDotDot,
    DotDotEq,
    DoubleQuote,
    Eq,
    EqEq,
    Ge,
    Gt,
    FatArrow,
    Le,
    LineComment(String),
    Lt,
    Minus,
    MinusEq,
    Or,
    OrEq,
    OrOr,
    Newline,
    Not,
    NotEq,
    Null,
    Floating(String),
    Numeric(usize),
    ParenLeft,
    ParenRight,
    PathSep,
    Percent,
    PercentEq,
    Plus,
    PlusEq,
    Pound,
    Question,
    RArrow,
    RawString(String),
    RawBinaryString(String),
    Semi,
    Shl,
    ShlEq,
    Shr,
    ShrEq,
    SingleQuote,
    Slash,
    SlashEq,
    Star,
    StarEq,
    String(String),
    Tab,
    Temp(String),  //for debugging
    Temp2(String), //for debugging
    Undefined,
    Underscore,
    WhiteSpace,
    Word(String),

    Stopped(String), //for debugging
}

#[allow(dead_code, clippy::upper_case_acronyms, clippy::enum_variant_names)]
#[derive(Debug, PartialEq, Clone, Eq, Hash)]
pub enum KeyWord {}

#[allow(dead_code, clippy::upper_case_acronyms, clippy::enum_variant_names)]
#[derive(Debug, PartialEq, Clone, Eq, Hash)]
pub enum TokenKind {
    Comment,
    CommentInLine,
    CommentBlockStart,
    CommentBlockStop,
    CRLF,

    DigitFloat(String),
    Digit(u32),
    EOF,
    KeyWord(String),
    Latin(char),
    Letter(String),
    CurlyLeft,
    ParenLeft,
    Number(String),
    Operator(String),
    Punctuation(char),
    CurlyRight,
    ParenRight,
    Temp(String),
    Variable(String),
    WhiteSpace,
    Word(String),
    Undefined,
}

///Licenses type for brew create field 'License'
#[allow(dead_code, clippy::upper_case_acronyms, clippy::enum_variant_names)]
#[derive(Debug, PartialEq, Copy, Clone, Eq)]
enum License {
    AppacheLicense2,
    GNUGeneralPublicLicenseV3,
    MITLicense,
    BSD2ClauseSimplifiedLicense,
    BSD3ClauseNewOrRevisedLicense,
    BoostSoftwareLicense1,
    CreativeCommonsZeroV1Universal,
    EclipsePublicLicense2,
    GNUAfferoGenralPublicLicenseV3,
    GNUGeneralPublicLicenseV2,
    GNULesserGeneralPublicLicenseV2_1,
    MozillaPublicLicense2,
    TheUnlicense,
}
