///Token field and description for tokenizer (lexer)
#[allow(dead_code, clippy::upper_case_acronyms, clippy::enum_variant_names)]
#[derive(Debug, PartialEq, Clone, Eq, Hash)]
pub enum Token {
    And,
    AndAnd,
    AndEq,
    Argument(String),
    At,
    BracketLeft,
    BracketRight,
    Caret,
    CaretEq,
    Colon,
    Comma,
    CommentInLine(String),
    CommentBlockStart(String),
    CommentBlockStop(String),
    CurlyBracketLeft,
    CurlyBracketRight,
    CRLF(String),
    Dollar,
    Dot,
    DotDot,
    Eq,
    EqEq,
    GreaterThanOrEqual,
    Ge,
    Gt,
    FatArrow,
    LessThanOrEqual,
    Le,
    Lt,
    Minus,
    MinusEq,
    Or,
    OrEq,
    OrOr,
    Not,
    NotEq,
    NumericFloat(String),
    Numeric(usize),
    ParenLeft,
    ParenRight,
    PathSep,
    Percent,
    PercentEq,
    Plus,
    PlusEq,
    Pound,
    Punctuation(String),
    Question,
    Reference(String),
    Semi,
    Shl,
    Shr,
    Slash,
    SlashEq,
    Star,
    StarEq,
    StatementDelimeter(String),
    String(String),
    Temp(String),
    Temp2(String),
    Undefined,
    Underscore,
    WhiteSpace,
    Word(String),

    Stopped(String), //for debugging
}

#[allow(dead_code, clippy::upper_case_acronyms, clippy::enum_variant_names)]
#[derive(Debug, PartialEq, Clone, Eq, Hash)]
pub enum TokenKind {
    Comment,
    CommentInLine,
    CommentBlockStart,
    CommentBlockStop,
    CRLF,

    DigitFloat(String),
    Digit(u32),
    EOF,
    KeyWord(String),
    Latin(char),
    Letter(String),
    CurlyLeft,
    ParenLeft,
    Number(String),
    Operator(String),
    Punctuation(char),
    CurlyRight,
    ParenRight,
    Temp(String),
    Variable(String),
    WhiteSpace,
    Word(String),
    Undefined,
}

///Licenses type for brew create field 'License'
#[allow(dead_code, clippy::upper_case_acronyms, clippy::enum_variant_names)]
#[derive(Debug, PartialEq, Copy, Clone, Eq)]
enum License {
    AppacheLicense2,
    GNUGeneralPublicLicenseV3,
    MITLicense,
    BSD2ClauseSimplifiedLicense,
    BSD3ClauseNewOrRevisedLicense,
    BoostSoftwareLicense1,
    CreativeCommonsZeroV1Universal,
    EclipsePublicLicense2,
    GNUAfferoGenralPublicLicenseV3,
    GNUGeneralPublicLicenseV2,
    GNULesserGeneralPublicLicenseV2_1,
    MozillaPublicLicense2,
    TheUnlicense,
}
